### ISSUE TITLE
The generated memory.npy file is too large when training

### ISSUE THREAD

**Issue by yangysc** [prabhatnagarajan/dqn#4]
Hello
     I ran the command `python train.py roms/breakout.bin`,  and, after training the agent about **499954**
 frames, **the generated memory.npy file is up to 9.5GB in size**.  Is it normal? Because my local 1080 Ti machine uses a  ssd small in volumn, it can't afford so large files. Then I tested the agent. It just **scored zero.** So I'm wondering maybe there's something wrong. 
    Thanks in advance!

**Comment by prabhatnagarajan** [comment]
Hi,
Unfortunately, this is probably the case. Each element of the replay memory stores one transition, which consists of a current state, and a next state. Each state is 4 84x84 frames, for a total of 8 84x84 frames. When you have 500,000 of these transitions, and you try and store it to disk, it can take up quite a bit of space. My advice would be to eliminate the memory.npy saving, and just run the agent flat out. 

Regarding the agent scoring zero, this is quite common. DQN performs quite poorly for a while. IF you look at slide 24 (http://joschu.net/docs/nuts-and-bolts.pdf), it notes that DQN is quite slow. On Breakout, I expect you'll see results after a few million frames (anywhere from 2 million to 5 million). Typically you have to leave it running overnight to see results. As such, a GPU is probably necessary. 

Closing this issue, please reopen it if you have any more questions.
